name: secure_db_example
description: Example app demonstrating the secure_db package functionality
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Reference to your secure_db package
  flutter_secure_storage: ^9.0.0
  secure_db:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true